name = "example-script-name"
main = "src/index.ts"
compatibility_date = "2024-06-03"

[[durable_objects.bindings]]
name = "EXAMPLE_DURABLE_OBJECT"
class_name = "ExampleDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["ExampleDurableObject"]
